const CUISINES_LIST = 'CUISINES_LIST';
const CUISINE_CREATE = 'CUISINE_CREATE';
const CUISINE_EDIT = 'CUISINE_EDIT';
const CUISINE_DELETE = 'CUISINE_DELETE';
const CUISINE_GET = 'CUISINE_GET';

const types = {
    CUISINES_LIST,
    CUISINE_CREATE,
    CUISINE_EDIT,
    CUISINE_DELETE,
    CUISINE_GET

}
export default types;