const RECIPES_LIST = 'RECIPES_LIST';
const RECIPE_CREATE = 'RECIPE_CREATE';
const RECIPE_EDIT = 'RECIPE_EDIT';
const RECIPE_DELETE = 'RECIPE_DELETE';
const types = {
    RECIPES_LIST,
    RECIPE_CREATE,
    RECIPE_EDIT,
    RECIPE_DELETE

}
export default types;