const RECIPES_REQUEST = 'RECIPES_REQUEST';
const RECIPES_SUCCESS = 'RECIPES_SUCCESS';
const RECIPES_FAILURE = 'RECIPES_FAILURE';

const types = {
    RECIPES_REQUEST,
    RECIPES_SUCCESS,
    RECIPES_FAILURE
}
export default types;